owner: formzillion # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: formzillion.com
    url: https://formzillion.com
  - name: app.formzillion.com
    url: https://app.formzillion.com
  - name: docs.formzillion.com
    url: https://docs.formzillion.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.formzillion.com
  # baseUrl: /your-repo-name
  logoUrl: https://formzillion.com/_next/static/media/metadata/favicon.a96c9259.ico
  name: Formzillion
  introTitle: "**Formzillion** is the open-source instant backend for forms."
  navbar:
    - title: Status
      href: /
    - title: Formzillion
      href: https://formzillion.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
